### PR TITLE
Feature space rule

### PR DESCRIPTION
**Pull request by akarsh**
- Add space rule
- Delete if statement that checks if username contains a space from the username validator
- Update makeSUT method in username validator unit test
-

### CODE REVIEW

**Review by ChristianSlanzi — CHANGES_REQUESTED** [review]
Well done, but there is an issue with the rule. How and why do you want to configure the space character? If the client is able to change it, le't say in "@", then it is not anymore a SpaceRule. I would not let the client being able to configure it. If, for any reason, should be configurable (like 2 spaces instead of one..or..I don't know), then I have also to assure that the rule keeps its meaning, so I would need some "validation" inside the rule for the rule itself.

3 changes:
- call it: NoSpacesRule
- make: private let space = ""
- change the message in "username must not contain spaces"

**Comment by akarsh** [comment]
> Well done, but there is an issue with the rule. How and why do you want to configure the space character? If the client is able to change it, le't say in "@", then it is not anymore a SpaceRule. I would not let the client being able to configure it. If, for any reason, should be configurable (like 2 spaces instead of one..or..I don't know), then I have also to assure that the rule keeps its meaning, so I would need some "validation" inside the rule for the rule itself.
> 
> 3 changes:
> 
>     * call it: NoSpacesRule
> 
>     * make: private let space = ""
> 
>     * change the message in "username must not contain spaces"

Nice suggestion Christian.
I did not understand how the empty string was able to pass. Does the contains method from String interpret the empty String - `""` as `" "` both same?

**Comment by ChristianSlanzi** [comment]
An empty string is empty, so it does not contain a space, so the validation rule is passing. We also don't want it to be empty, but for that we need another rule, like as the min length rule. There it should not pass. In our validator we must check that all rules are passing, or putting it in other terms, returning false when one of the rules is not passing.

**Comment by ChristianSlanzi** [comment]
Oh sorry, my typing mistake. It should be 
private let space = " "

otherwise it is not a space ;-)

**Comment by akarsh** [comment]
Thank you Christian for the explanation.
I refactored it.

**Comment by ChristianSlanzi** [comment]
Perfect. I merge the pr.

**Pull request merged**
