### PR TITLE
Username validator

### PR DESCRIPTION
**Pull request by akarsh**
- Added unit tests for validating username
- UsernameValidator is added to the group "DataAccess"

### CODE REVIEW

**Comment by akarsh** [comment]
@ChristianSlanzi please review this pull request.

**Review by ChristianSlanzi — CHANGES_REQUESTED** [review]
I'd wish a couple of changes before approving the pull request.

- Rename "isValid" into "validate". Read your code, left to right, to choose the proper names. 
if UsernameValidator().isValid("pippo") .... sounds like asking if the Validator is valid, not the argument you passed ... isValid sounds like a property check, not like an operation. E.g., string.isEmpty, value.isValid  

- Don't chain the if statements, you don't need to, every if contains a return. It's also a general good habit not to write long if then else, a switch case is better to handle multiple cases. But here just keep each if statement isolated. In the next step I'll ask you to replace the if statements with something else.... ;-) (we'll inject the rules). The last return true should also be isolated, better indicating that the function is returning a value.

- Move the UsernameValidator under the BusinessLogic group. DataAccess is the raw access to datas, like as database and networking. You might think that user input is "data access", but the interpretation of the input, the meaning you are giving to it, in this case a username and a validator logic, is definitely business logic.

**Comment by akarsh** [comment]
> I'd wish a couple of changes before approving the pull request.
> 
>     * Rename "isValid" into "validate". Read your code, left to right, to choose the proper names.
>       if UsernameValidator().isValid("pippo") .... sounds like asking if the Validator is valid, not the argument you passed ... isValid sounds like a property check, not like an operation. E.g., string.isEmpty, value.isValid
> 
>     * Don't chain the if statements, you don't need to, every if contains a return. It's also a general good habit not to write long if then else, a switch case is better to handle multiple cases. But here just keep each if statement isolated. In the next step I'll ask you to replace the if statements with something else.... ;-) (we'll inject the rules). The last return true should also be isolated, better indicating that the function is returning a value.
> 
>     * Move the UsernameValidator under the BusinessLogic group. DataAccess is the raw access to datas, like as database and networking. You might think that user input is "data access", but the interpretation of the input, the meaning you are giving to it, in this case a username and a validator logic, is definitely business logic.

Thanks for the review Christian.
I made the changes in this commit 1cf738c

**Comment by ChristianSlanzi** [comment]
Great! I'm going to merge the pr. 
I forgot one further refactor enhancement, but you can do it in the next pull request. You can remove the check "username.isEmpty" because it is logical included in "username.count <= 5" :-)

**Comment by akarsh** [comment]
> Great! I'm going to merge the pr.
> I forgot one further refactor enhancement, but you can do it in the next pull request. You can remove the check "username.isEmpty" because it is logical included in "username.count <= 5" :-)

Yes I agree with you the isEmpty is not required.
I removed it in this commit
789aaeb

**Pull request merged**
